// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjejxV3oKtM5CchhRheuzcPpPsgODnpJc',
    appId: '1:516171780775:web:22b64890af524f37ef0182',
    messagingSenderId: '516171780775',
    projectId: 'ru-smart-uespi-vitor',
    authDomain: 'ru-smart-uespi-vitor.firebaseapp.com',
    storageBucket: 'ru-smart-uespi-vitor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8uzB4_EJo_gbXetpAw2j8WAXNDjVMdL0',
    appId: '1:516171780775:android:25d22547016589adef0182',
    messagingSenderId: '516171780775',
    projectId: 'ru-smart-uespi-vitor',
    storageBucket: 'ru-smart-uespi-vitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZI9I_aiqfyzjyf5nJgL45y26s0azdr0',
    appId: '1:516171780775:ios:483ff6d0be3ca874ef0182',
    messagingSenderId: '516171780775',
    projectId: 'ru-smart-uespi-vitor',
    storageBucket: 'ru-smart-uespi-vitor.firebasestorage.app',
    iosBundleId: 'com.example.rusmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqZI9I_aiqfyzjyf5nJgL45y26s0azdr0',
    appId: '1:516171780775:ios:483ff6d0be3ca874ef0182',
    messagingSenderId: '516171780775',
    projectId: 'ru-smart-uespi-vitor',
    storageBucket: 'ru-smart-uespi-vitor.firebasestorage.app',
    iosBundleId: 'com.example.rusmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjejxV3oKtM5CchhRheuzcPpPsgODnpJc',
    appId: '1:516171780775:web:aec170ac708cb106ef0182',
    messagingSenderId: '516171780775',
    projectId: 'ru-smart-uespi-vitor',
    authDomain: 'ru-smart-uespi-vitor.firebaseapp.com',
    storageBucket: 'ru-smart-uespi-vitor.firebasestorage.app',
  );
}
